name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    name: Build & run docker image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build .
